# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160114_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
